### ISSUE TITLE
Apollo plugin skeleton, initial communication with server

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-plugin-apollo#1]
Initial plugin that .... does something with an existing Apollo server.

**Comment by nathandunn** [comment]
FYI https://github.com/GMOD/apollo-gmod-js

This is explcitly put in for Apollo 3 (i.e. no security), but we could rename this to apollo3 and create another one called apollo2 as it should be a separate library.

**Comment by rbuels** [comment]
I'd say this is done
