### ISSUE TITLE
Have collaboration server read a GFF3 into memory

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#13]
- GFF3 file location is in `.env` file
- When server starts, it looks for the GFF3 file at that location and uses `fs` to read the whole
- The file text is then parsed with [`@gmod/gff`](https://github.com/GMOD/gff-js) into feature objects

**Comment by kyostiebi** [comment]
GFF3 file is loaded into cache that has been set 'never expire'. Cache size has now been set 100 000 key-value -pairs (i.e. rows in GFF3 file)

**Comment by garrettjstevens** [comment]
Done in #25
