### ISSUE TITLE
Assign unique IDs to features

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#40]
When the GFF3 is read from the file when the server starts:
- Check each feature to see if it has a unique Apollo ID, something like:
```json
{
  "attributes": {
    "ID": ["cds00001"],
    "Parent": ["mRNA00001"],
    "apollo_id": "1ccdfd84-587f-49aa-be63-8dab88a61b1b"
}
```
- If the feature does not have an apollo_id, generate one for it
- Once the whole file has been checked, overwrite the original file to make sure all ids are recorded in that file

**Comment by kyostiebi** [comment]
Apollo_id must be also added to each child feature recursively
