### ISSUE TITLE
Create MongoDB schema for features

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#50]
We need some sort of initial schema for features collections in MongoDB. We can then iterate on it as we go.

@kyostiebi and I talked and decided that top-level features will each have their own document, and child features will be inside the parent feature document.

@kyostiebi, could you open a draft PR with just the schema code? Don't worry about the code for loading features or anything, we just need the schema for now.

**Comment by garrettjstevens** [comment]
@kyostiebi as discussed earlier today, we'll go over the schemas tomorrow at our meeting. Go ahead and put the schemas in this branch: https://github.com/GMOD/jbrowse-plugin-apollo/tree/mongodb_schemas. That way we can put them in a separate PR. I modeled the structure of those files/directories in that branch after this example: https://github.com/nestjs/nest/tree/master/sample/06-mongoose.

**Comment by kyostiebi** [comment]
New repo (IssueMongoDb) has been created that contains very first draft of Mongo Db schema. However, it contains now only Assemblies, RefSeqs and Features. We need to add Roles, Users, ChangeLogs etc. later. In the new repo, apollo_id has been replaced by featureId.
