### ISSUE TITLE
Create basic Feature module endpoints

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#52]
This will have:
- ~~the MongoDB schema for features~~
- A feature controller that does
  - ~~GET: /features/getFeatures?seq_id=chr1&start=1000&end=2000~~
  - GET: /features/:featureId
  - GET: /features (this returns all features)

~~When retrieving features by range, top-level features with all their children are returned.~~

When retrieving features by id, the features and any of its children are returned, but not any of its parent or sibling features.

**Comment by garrettjstevens** [comment]
@kyostiebi The feature schema (and other schemas) are now in place on the main branch and ready for the modules.

**Comment by kyostiebi** [comment]
New repo (Issue52) has been created and it contains:
- new modules: assemblies, features and refuses
- new folder 'schemas' that contains first schemas for Assemblies, RefSeqs and Features -collections
- GET: features/getFeatures and GET: /features/:featureId -end points

**Comment by kyostiebi** [comment]
Should we also pass assemblyId as GET parameter because the db may contain several assemblies?

**Comment by garrettjstevens** [comment]
@kyostiebi yes, we should. Also, I rebased that branch so that it didn't conflict with the changes on main and opened a PR so I could add some review comments: https://github.com/GMOD/jbrowse-plugin-apollo/pull/54

**Comment by garrettjstevens** [comment]
This is now updated so that it will come after #59, and does not include the `features/getFeatures` range request.

**Comment by kyostiebi** [comment]
This is now implemented in branch Issue52B.
