### ISSUE TITLE
Use stream when uploading GFF3

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#65]
By default Nest's `FileInterceptor` loads the whole uploaded file into memory before using it. We'll need to support streaming uploads for larger GFF3s, which means creating a custom storage engine for multer. More info here: https://github.com/expressjs/multer/blob/master/StorageEngine.md

**Comment by garrettjstevens** [comment]
More details:

An outline for a custom storage engine might look like this:

```ts
import { StorageEngine } from 'multer'

export class MongoDBStorage implements StorageEngine {
  async _handleFile(
    req: Express.Request,
    file: Express.Multer.File,
    cb: (error?: unknown, info?: Partial<Express.Multer.File>) => void,
  ) {
    for await (const chunk of file.stream) {
      console.log(chunk.toString())
    }
    cb(null, file)
  }

  _removeFile(
    req: Express.Request,
    file: Express.Multer.File,
    cb: (error: Error | null) => void,
  ) {
    console.log(file)
  }
}

```

Then it would be added to the interceptor in `packages/apollo-collaboration-server/src/features/features.controller.ts` like this:

```ts
@UseInterceptors(FileInterceptor('file', { storage: new MongoDBStorage() }))
```

**Comment by garrettjstevens** [comment]
@rbuels we're still setting up a way to easily load data into our db (see #67), but this should get you started for now. To add the assembly and ref seqs you'll need, you can run these:
```
curl -X POST http://localhost:3999/assemblies -d '{"name":"volvox","_id":"624f33ed60328ade9b6b322f"}' -H "Content-Type: application/json"
curl -X POST http://localhost:3999/assemblies -d '{"name":"ctgA","length":50000,"assembly":"624f33ed60328ade9b6b322f"}' -H "Content-Type: application/json"
curl -X POST http://localhost:3999/assemblies -d '{"name":"ctgB","length":6078,"assembly":"624f33ed60328ade9b6b322f"}' -H "Content-Type: application/json"
```
Then to load a GFF3 into the database, you can do this (from the apollo-collaboration-server directory)
```
curl http://localhost:3999/features/importGFF3 -F file=@./test/data/volvox.sort.fasta.gff3 -F 'assembly=624f33ed60328ade9b6b322f'
```

**Comment by cmdcolin** [comment]
interloper here, but i would consider writing to disk in a tmpdir before doing a streams-only approach. streams only is quite challenging and if file fails to upload midway, that could also be a problem

might be an option to multer https://stackoverflow.com/a/64632458/2129219

**Comment by garrettjstevens** [comment]
Closing in favor of #79
