### ISSUE TITLE
Make a way to load test data into MongoDB

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#67]
Create some way (possible a `.mongodb` playground file) that allows you to load all necessary data for one organism into an empty MongoDB instance. That includes Assembly, RefSeqs, RefSeqChunks, and Features. This will allow us to load test data without relying on the UI.

**Comment by kyostiebi** [comment]
@garrettjstevens now, there is also schema definition and test data for refSeqChunks -collection.
