### ISSUE TITLE
Create changeLog schema

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#69]
This will go in `apollo-schemas`. It will be used in the change module that already exists. Should have info about user, time, assembly, and affected feature IDs, as well as the change itself.

Sample TS interface, to be converted to Mongoose schema:

```ts
interface Change {
  user: string // User's object ID
  time: number // timestamp
  assembly: string // Assembly's object ID
  featureIds: string[] // feature IDs of affected features
  change: JSON // serialized change
  reverts?: string // object ID of change if this reverts a previous change
}
```

At the end of `submitChange` in `packages/apollo-collaboration-server/src/change/change.service.ts`, add a new change to the database. `submitChange` will then return the objectID of the change that got added to the changelog so the frontend can use it when submitting an undo.

**Comment by garrettjstevens** [comment]
Sample TS interface, to be converted to Mongoose schema:
```ts
interface Change {
  user: string // User's object ID
  time: number // timestamp
  assembly: string // Assembly's object ID
  featureIds: string[] // object IDs of affected features
  change: JSON // serialized change
}
```

**Comment by kyostiebi** [comment]
A couple questions for clarification:
- assembly -property: where shall we get it? Currently, assembly is not part of changeObject.
- featureIds -property: This should contain array of featureIds - not array of object ids of features because under one object id there can be several child features and then we cannot necessary identify the correct (child)feature.
- If one changeObject contains several changes, I guess that then we need to create changeLog document for each change, right?

**Comment by garrettjstevens** [comment]
> assembly -property: where shall we get it? Currently, assembly is not part of changeObject.

Let's add assembly (as an assemblyId) to the Change object

> featureIds -property: This should contain array of featureIds - not array of object ids of features because under one object id there can be several child features and then we cannot necessary identify the correct (child)feature.

Good point, I updated that in the description.

> If one changeObject contains several changes, I guess that then we need to create changeLog document for each change, right?

No need to do that. If we have several changes, they will always be grouped under some type of top-level change.

> ChangeObject contains changeId for each change. I guess we need to save changeId also into Mongo?

It's `changedIds`, not `changeIds`. It's the same thing as `featureIds`, a list of the IDs of features that were changed. We should probably standardize on one or the other.

**Comment by kyostiebi** [comment]
How about user information? Is backend going to extract it from token that is used to authorise endpoint call OR is will user information be provided by UI? If UI will provide user information then I guess user -information should be included in Change -object?
